### ISSUE TITLE
fill in the readme file

### ISSUE THREAD

**Issue by CWWhitney** [Issoufou-Liman/decisionSupportExtra#1]
@Issoufou-Liman could you write something descriptive in the readme file so that we have an overview of what you are working on here? It looks interesting.
Thanks

**Comment by Issoufou-Liman** [comment]
@CWWhitney , add something to README as per #1

**Comment by CWWhitney** [comment]
Nice. Can you add me as a collaborator so that I can change the file too? That would be nice. Notice that the information about CRAN is empty. This is because you have not submitted it as a package.. It may not be the best html to include here. 
We could create a bitbucket to github.io like for an html file if you want to make a small webpage about what the package does..

**Comment by CWWhitney** [comment]
Nice work. Now can we start a private repository for your paper? We should get moving with that. :)

**Comment by CWWhitney** [comment]
This is resolved. You can remove it.
